import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#dbe1ff",
        "tertiary-container": "#2e1a00",
        "secondary-fixed-dim": "#b4c5ff",
        "on-tertiary-container": "#bb7700",
        "surface-tint": "#4e6077",
        "on-primary-container": "#7587a0",
        error: "#ba1a1a",
        "inverse-surface": "#213145",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        secondary: "#0051d5",
        "primary-container": "#0b1f33",
        "on-surface-variant": "#44474c",
        surface: "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "on-error-container": "#93000a",
        "primary-fixed": "#d1e4ff",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed": "#081d30",
        "on-secondary-container": "#fefcff",
        "on-secondary-fixed-variant": "#003ea8",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed": "#00174b",
        "error-container": "#ffdad6",
        "surface-container": "#e5eeff",
        "outline-variant": "#c4c6cd",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-background": "#0b1c30",
        tertiary: "#0b0400",
        "primary-fixed-dim": "#b5c8e3",
        "secondary-container": "#316bf3",
        primary: "#00050e",
        outline: "#74777d",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-high": "#dce9ff",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-highest": "#d3e4fe",
        "surface-variant": "#d3e4fe",
        "on-error": "#ffffff",
        background: "#f8f9ff",
        "on-surface": "#0b1c30",
        "on-primary-fixed-variant": "#36485e",
        "inverse-primary": "#b5c8e3",
        "status-success": "#059669",
        "status-success-bg": "#ecfdf5",
        "status-success-border": "#a7f3d0",
        "status-warning": "#d97706",
        "status-warning-bg": "#fffbeb",
        "status-warning-border": "#fde68a",
        "status-error": "#dc2626",
        "status-error-bg": "#fef2f2",
        "status-error-border": "#fecaca",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-2xl": "2rem",
        "space-3xs": "0.125rem",
        "space-3xl": "3rem",
        "space-md": "0.75rem",
        "margin-mobile": "1rem",
        "space-4xl": "4rem",
        "space-xs": "0.375rem",
        "space-2xs": "0.25rem",
        "margin-desktop-wide": "3rem",
        "space-sm": "0.5rem",
        "gutter-desktop-wide": "2rem",
        "gutter-mobile": "1rem",
        margin: "2rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        gutter: "1.5rem",
        "space-base": "1rem",
      },
      fontFamily: {
        "headline-xl-mobile": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "display-hero-mobile": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-xl": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "headline-lg-mobile": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "headline-md": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "label-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "data-mono": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "display-hero": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "headline-sm": ["var(--font-manrope)", "Manrope", "sans-serif"],
      },
      fontSize: {
        "headline-xl-mobile": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "label-caps": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.06em", fontWeight: "700" }],
        "headline-xl": ["2.5rem", { lineHeight: "3rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-lg-mobile": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["1.375rem", { lineHeight: "1.875rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.005em", fontWeight: "500" }],
        "data-mono": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-hero": ["3.5rem", { lineHeight: "4rem", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5rem", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["1.875rem", { lineHeight: "2.375rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.625rem", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      boxShadow: {
        tier2: "0 1px 3px 0 rgba(11, 31, 51, 0.04), 0 4px 12px 0 rgba(11, 31, 51, 0.03)",
        tier3: "0 4px 6px -1px rgba(11, 31, 51, 0.05), 0 10px 24px -3px rgba(11, 31, 51, 0.08)",
      },
      maxWidth: {
        canvas: "1440px",
      },
    },
  },
  plugins: [],
};

export default config;
